owner: amafarja  # your GitHub username
repo: upptime    # your repo name

sites:
  - name: LogesTechs
    url: https://apisv2.logestechs.com/api/guests/customer/android/min-version

status-website:
  cname: status.logestechs.com  # remove this line if you're not using a custom domain
  name: LogesTechs Status
  introTitle: "**LogesTechs API Status**"
  introMessage: Live status of LogesTechs services.
  logoUrl: https://upptime.js.org/img/icon.svg  # replace with your logo URL later
  theme: light
